### ISSUE TITLE
Running  `./iview-cli --programme`  crashes at UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 42: ordinal not in range(128)

### ISSUE THREAD

**Issue by shasheene** [vadmium/python-iview#13]
Hi, haven't seen python-iview for a very long time. Glad it's still exists

On my Raspberry Pi (Linux raspbmc 3.12.31 #2 PREEMPT Wed Oct 29 09:24:56 UTC 2014 armv6l GNU/Linux)
> $ ./iview-cli --programme
crashes halfway:
> [...]
> Giggle And Hoot Funky Owl: Monkey Owl Dance	(kids/gigglehoot_04_81.mp4)
> Traceback (most recent call last):
>  File "./iview-cli", line 292, in <module>
>    main()
>  File "./iview-cli", line 271, in main
>    programme()
>  File "./iview-cli", line 33, in programme
>    return category('index')
>  File "./iview-cli", line 41, in category
>    print_series_items(series['items'], indent='\t')
>  File "./iview-cli", line 69, in print_series_items
>    item['title'], item['url']))
>UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 42: ordinal not in >range(128)

Strangely enough it works on my Linux Mint desktop PC:
> [...]
> Giggle And Hoot Funky Owl: Monkey Owl Dance     (kids/gigglehoot_04_81.m
p4)
> Giggle And Hoot Gigglemobile: Fixing Hoot’s Car (kids/gigglehoot_04_46.m
p4)
> [...]

**Comment by vadmium** [comment]
Thanks for the report. This shouldn’t be hard to fix, and I will try to push a fix tomorrow. It just needs to print the programme names using a non-strict error handler like “replace”. I assume your Pi isn’t set up to use a UTF-8 locale, so it defaults to ASCII only, and the “Hoot’s Car” title has a non-ASCII apostrophe in it.

**Comment by vadmium** [comment]
I pushed some changes which includes a fix for this. Now you should see the apostrophe is replace with a question mark and it continues on.

```
$ LC_ALL=C iview-cli -s 3114043
[. . .]
Giggle And Hoot Gigglemobile: Fixing Hoot?s Car	(kids/gigglehoot_04_46.mp4)
[. . .]
```
